# Generated by Django 5.0.4 on 2024-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(max_length=200)),
                ('audit', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=2000)),
            ],
        ),
    ]
