# Generated by Django 5.0.4 on 2024-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='audit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
